name: PHP7.4+MySQL8.0

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: baijunyao/mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: laravel_bjyblog
          MYSQL_DATABASE: laravel_bjyblog
    container:
      image: baijunyao/php:7.4-local
      volumes:
        - /__w/laravel-bjyblog/laravel-bjyblog:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
          php artisan key:generate
          php artisan passport:keys
          php artisan migrate
          php artisan db:seed
      - name: Test
        run: |
          ./vendor/bin/phpunit
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@feature/add-default-value
        if: always()
